### create article
POST localhost:8080/api/v1/article/moderator/create
Content-Type: application/json
Authorization: Basic bW9kZXJhdG9yOjEyMzQ1

{
  "title": "Davlat",
  "description": "Iqtisod",
  "content": "Idi naxuy",
  "article_type_id": "1"

}

### update
PUT localhost:8080/api/v1/article/moderator/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NTg0NDYsImlkIjoyMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4OTk0NDg0NiwiaXNzIjoiS3VuLnV6IHRlc3QgcG9ydGFsaSJ9.kwymWJbxFhtKH6IKdyDv6A62ApWo7Eut0VnXFZhFORE34OWn2rXgJMrkBNiczhg2X9K8UX143FaKoiczIwtfTw

{
  "title": "Ko'tbachcha",
  "description": "Ko'ntucha",
  "content": "Ko'tcha 2023",
  "region_id": 1,
  "category_id": 2
}

### delete
DELETE localhost:8080/api/v1/article/moderator/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NTg0NDYsImlkIjoyMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4OTk0NDg0NiwiaXNzIjoiS3VuLnV6IHRlc3QgcG9ydGFsaSJ9.kwymWJbxFhtKH6IKdyDv6A62ApWo7Eut0VnXFZhFORE34OWn2rXgJMrkBNiczhg2X9K8UX143FaKoiczIwtfTw

### change status
PUT localhost:8080/api/v1/article/moderator/change/status/1
Authorization: Basic bW9kZXJhdG9yOjEyMzQ1

### get last 5 article
GET localhost:8080/api/v1/article/moderator/getLastArticle
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NTg0NDYsImlkIjoyMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4OTk0NDg0NiwiaXNzIjoiS3VuLnV6IHRlc3QgcG9ydGFsaSJ9.kwymWJbxFhtKH6IKdyDv6A62ApWo7Eut0VnXFZhFORE34OWn2rXgJMrkBNiczhg2X9K8UX143FaKoiczIwtfTw


### get 5 value
GET localhost:8080/api/v1/article/moderator/getLastFiveArticle
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAyOTM5MjAsImlkIjoyMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY5MDM4MDMyMCwiaXNzIjoiS3VuLnV6IHRlc3QgcG9ydGFsaSJ9.VkShszvlB6zvhUQviLGTvOYLWOYn_E8OCXePB1taWXi5KC0ahw4vYGyc1l-FIaAOXwNLv8uOLunOvluE5utF7w

### get not given id
GET localhost:8080/api/v1/article/moderator/notGivenId/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA5MDM3OTYsImlkIjoyMCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY5MDk5MDE5NiwiaXNzIjoiS3VuLnV6IHRlc3QgcG9ydGFsaSJ9.odP3__iZqqBeaB804quDPFwncwlZnY5Vb5hI12c9OQrfEB_WnVdmqMTomoioeJceDnfc9hfBTIred8dHWbLepg

### get by id and lang
GET localhost:8080/api/v1/article/moderator//getIdAndLang/1
Authorization: Basic bW9kZXJhdG9yOjEyMzQ1

### get last 4 article
GET localhost:8080/api/v1//article/getLast4/1/1
Authorization: Basic bW9kZXJhdG9yOjEyMzQ1










