### create profile
POST localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Qoplonber",
  "surname": "Ergashev",
  "email": "qoplon1254@gmail.com",
  "phone": "984563423",
  "password": "qoplon1122",
  "role": "MODERATOR"
}

### update profile
PUT localhost:8080/profile/5
Content-Type: application/json

{
  "name": "Qo'yjon",
  "surname": "Sigirov",
  "email": "sog'uvchi2023@gmail.com",
  "phone": "998765433",
  "password": "sug'iluvchi123"
}

### get pagination profile list
GET localhost:8080/profile/pagination?page=2&size=2


### delete profile
DELETE localhost:8080/profile/2

### get all
GET localhost:8080/profile/all

### filter
POST localhost:8080/profile/filter?page=1&size=10
Content-Type: application/json

{
  "name": "Ali"
}