### create profile
POST localhost:8080/api/v1/profile/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzODE4ODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NjgyODQsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.Av98682qj0B4U2lIIKRg5Yq0RgLvB-ldmFq-3GLhU1-L7NH3KHJRKBqm8KlIcVvvzBgpufZqT5AcQ_IRhrqI_w

{
  "name": "Mo'ydinjon",
  "surname": "Qambarov",
  "email": "Mo'ydin345@gmail.com",
  "phone": "987676767",
  "password": "12345",
  "role": "MODERATOR"
}

### update profile
PUT localhost:8080/api/v1/profile/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzODE4ODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NjgyODQsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.Av98682qj0B4U2lIIKRg5Yq0RgLvB-ldmFq-3GLhU1-L7NH3KHJRKBqm8KlIcVvvzBgpufZqT5AcQ_IRhrqI_w

{
  "name": "Qo'yjon",
  "surname": "Sigirov",
  "email": "sog'uvchi2023@gmail.com",
  "phone": "998765433",
  "password": "sug'iluvchi123"
}

### udate detail
PUT localhost:8080/api/v1/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzODE4ODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NjgyODQsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.Av98682qj0B4U2lIIKRg5Yq0RgLvB-ldmFq-3GLhU1-L7NH3KHJRKBqm8KlIcVvvzBgpufZqT5AcQ_IRhrqI_w

{
  "name": "Adminjon",
  "surname": "Adminov"
}

### get pagination profile list
GET localhost:8080/api/v1/profile/pagination?page=2&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzODE4ODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NjgyODQsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.Av98682qj0B4U2lIIKRg5Yq0RgLvB-ldmFq-3GLhU1-L7NH3KHJRKBqm8KlIcVvvzBgpufZqT5AcQ_IRhrqI_w


### delete profile
DELETE localhost:8080/api/v1/profile/19
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzODE4ODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NjgyODQsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.Av98682qj0B4U2lIIKRg5Yq0RgLvB-ldmFq-3GLhU1-L7NH3KHJRKBqm8KlIcVvvzBgpufZqT5AcQ_IRhrqI_w


### get all
GET localhost:8080/api/v1/profile/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzODE4ODQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NjgyODQsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.Av98682qj0B4U2lIIKRg5Yq0RgLvB-ldmFq-3GLhU1-L7NH3KHJRKBqm8KlIcVvvzBgpufZqT5AcQ_IRhrqI_w

### filter
POST localhost:8080/api/v1/profile/filter?page=1&size=10
Content-Type: application/json

{
  "name": "Ali"
}