### create region
POST localhost:8080/api/v1/region/admin/create
Content-Type: application/json
Authorization: Basic

{
  "order_number": "12",
  "name_uz": "Namangan",
  "name_ru": "Наманган",
  "name_en": "Namangan"
}

### update region
PUT localhost:8080/api/v1/region/admin/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NDkwNTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk5MzU0NTcsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.mV2HaHHJBa8yvqrn6bJnYorFsXn-rhMM1G6H3gd3aQQoiYfhk0WaK_gTKVC_P6RrTSEYgVYdnXnNfvN9STmO-w

{
  "order_number": "12",
  "name_uz": "Jizzax",
  "name_ru": "Джизак",
  "name_en": "Djizak"
}

### delete region
DELETE localhost:8080/api/v1/region/admin/12
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NDkwNTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk5MzU0NTcsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.mV2HaHHJBa8yvqrn6bJnYorFsXn-rhMM1G6H3gd3aQQoiYfhk0WaK_gTKVC_P6RrTSEYgVYdnXnNfvN9STmO-w

### get all
GET localhost:8080/api/v1/region/admin/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NDkwNTcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk5MzU0NTcsImlzcyI6Ikt1bi51eiB0ZXN0IHBvcnRhbGkifQ.mV2HaHHJBa8yvqrn6bJnYorFsXn-rhMM1G6H3gd3aQQoiYfhk0WaK_gTKVC_P6RrTSEYgVYdnXnNfvN9STmO-w

### get by language uz
GET localhost:8080/region/lang
